### ISSUE TITLE
Panel is Too Dangerous

### ISSUE THREAD

**Issue by Tromino** [mitchfizz05/DangerousPanel#3]

**Comment by mitchfizz05** [comment]
This is an intended feature.

Dangerous Panel accepts no responsibility for any physical injury, emotional trauma or death incurred by using this product.

**Comment by Tromino** [comment]
Thank you. I've always wanted to die. This product is perfect for that.

Je vous remercie. J'ai toujours voulu mourir. Ce produit est parfait pour cela.

Gracias. Siempre he querido morir. Este producto es perfecto para eso.

Köszönöm. Mindig is szerettem volna meghalni. Ez a termék tökéletes, hogy.

Tack. Jag har alltid velat dö. Denna produkt är perfekt för detta.

ありがとうございました。私はいつも死にたいと思っていました。この製品は、そのために最適です。

אדאנק. איך ווע שטענדיק געוואלט צו שטאַרבן. דעם פּראָדוקט איז גאנץ פֿאַר אַז.

مننه. ما تل غوښتل چې مړه شي. دا د توليد لپاره چې کامل دی.

متشکرم. من همیشه می خواستم برای مردن. این محصول مناسب برای آن است.
