### ISSUE TITLE
Panel is Not Dangerous Enough

### ISSUE THREAD

**Issue by Tromino** [mitchfizz05/DangerousPanel#4]
I expected to die. This did not happen.
I want my money back.

Yo esperaba a morir. Esto no sucedió.
Quiero mi dinero de vuelta.

Je pensais mourir. Cela n'a pas eu lieu.
Je veux qu'on me rende mon argent.

Mi aspettavo di morire. Questo non è accaduto.
Voglio i miei soldi indietro.

Eu esperava morrer. Isso não aconteceu.
Eu quero meu dinheiro de volta.

Jag förväntas dö. Detta skedde inte.
Jag vill ha tillbaka mina pengar.

Pričakoval sem, da umre. To se ni zgodilo.
Hočem svoj denar nazaj.

Ég bjóst við að deyja. Þetta gerðist ekki.
Ég vil peningana mína til baka.

Tôi nghĩ rằng sẽ chết. Điều này đã không xảy ra.
Tôi muốn lấy lại tiền của mình.

ველოდი, რომ იღუპება. ეს ასე არ მოხდა.
მე მინდა ჩემი ფული.

كنت أتوقع أن يموت. وهذا لم يحدث.
اريد استرجاع نقودي.

איך דערוואַרט צו שטאַרבן. דאס האט נישט פּאַסירן.
איך ווילן מיין געלט צוריק.

我預計死亡。這並沒有發生。
我想要回我的錢。

Я ожидал, чтобы умереть. Этого не произошло.
Я хочу свои деньги назад.

**Comment by mitchfizz05** [comment]
I apologise for the inconvenience.

Please call the customer care number at 1800-6969-6969 and we will look into this for you.
